name: Pull Request

on:
  pull_request:
    branches: [develop]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test -- --watchAll=false --passWithNoTests

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Check formatting
        run: npm run format
